version: '3.8'

services:
  fastmcp-app:
    build: .
    container_name: fastmcp-app
    environment:
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - TRANSPORT_MODE=http
      - HOST=0.0.0.0
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
